openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/tasks:
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Task created successfully.'
                  data:
                    id: 1
                    title: 'Buy groceries'
                    description: 'Milk, Bread, Cheese'
                    is_completed: false
                    created_at: '2023-01-01T00:00:00.000000Z'
                    updated_at: '2023-01-01T00:00:00.000000Z'
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Task created successfully.'
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      title:
                        type: string
                        example: 'Buy groceries'
                      description:
                        type: string
                        example: 'Milk, Bread, Cheese'
                      is_completed:
                        type: boolean
                        example: false
                      created_at:
                        type: string
                        example: '2023-01-01T00:00:00.000000Z'
                      updated_at:
                        type: string
                        example: '2023-01-01T00:00:00.000000Z'
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Validation errors'
                  data:
                    title:
                      - 'The title field is required.'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Validation errors'
                  data:
                    type: object
                    properties:
                      title:
                        type: array
                        example:
                          - 'The title field is required.'
                        items:
                          type: string
      tags:
        - 'Task Management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'The title of the task.'
                  example: 'Buy groceries'
                description:
                  type: string
                  description: 'The description of the task.'
                  example: 'Milk, Bread, Cheese'
                is_completed:
                  type: boolean
                  description: 'The completion status of the task.'
                  example: false
              required:
                - title
      security: []
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Tasks retrieved successfully.'
                  data:
                    -
                      id: 1
                      title: 'Task title'
                      description: 'Task description'
                      is_completed: false
                      created_at: '2023-01-01T00:00:00.000000Z'
                      updated_at: '2023-01-01T00:00:00.000000Z'
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Tasks retrieved successfully.'
                  data:
                    type: array
                    example:
                      -
                        id: 1
                        title: 'Task title'
                        description: 'Task description'
                        is_completed: false
                        created_at: '2023-01-01T00:00:00.000000Z'
                        updated_at: '2023-01-01T00:00:00.000000Z'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        title:
                          type: string
                          example: 'Task title'
                        description:
                          type: string
                          example: 'Task description'
                        is_completed:
                          type: boolean
                          example: false
                        created_at:
                          type: string
                          example: '2023-01-01T00:00:00.000000Z'
                        updated_at:
                          type: string
                          example: '2023-01-01T00:00:00.000000Z'
      tags:
        - 'Task Management'
      security: []
  '/api/tasks/{id}':
    get:
      summary: 'Display the specified resource.'
      operationId: displayTheSpecifiedResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Task retrieved successfully.'
                  data:
                    id: 1
                    title: 'Buy groceries'
                    description: 'Milk, Bread, Cheese'
                    is_completed: false
                    created_at: '2023-01-01T00:00:00.000000Z'
                    updated_at: '2023-01-01T00:00:00.000000Z'
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Task retrieved successfully.'
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      title:
                        type: string
                        example: 'Buy groceries'
                      description:
                        type: string
                        example: 'Milk, Bread, Cheese'
                      is_completed:
                        type: boolean
                        example: false
                      created_at:
                        type: string
                        example: '2023-01-01T00:00:00.000000Z'
                      updated_at:
                        type: string
                        example: '2023-01-01T00:00:00.000000Z'
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Task not found'
                  data: null
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Task not found'
                  data:
                    type: string
                    example: null
      tags:
        - 'Task Management'
      security: []
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n  \"success\": true,\n  \"message\": \"Task updated successfully.\",\n  \"data\": {\n    \"id\": 1,\n    \"title\": \"Buy groceries\n    \"description\": \"Milk, Bread, Cheese\",\n    \"is_completed\": false,\n    \"created_at\": \"2023-01-01T00:00:00.000000Z\",\n    \"updated_at\": \"2023-01-01T00:00:00.000000Z\"\n  }\n}"
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Task not found'
                  data: null
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Task not found'
                  data:
                    type: string
                    example: null
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Validation errors'
                  data:
                    title:
                      - 'The title field is required.'
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Validation errors'
                  data:
                    type: object
                    properties:
                      title:
                        type: array
                        example:
                          - 'The title field is required.'
                        items:
                          type: string
      tags:
        - 'Task Management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'The title of the task.'
                  example: 'Buy groceries'
                description:
                  type: string
                  description: 'The description of the task.'
                  example: 'Milk, Bread, Cheese'
                is_completed:
                  type: boolean
                  description: 'The completion status of the task.'
                  example: false
              required:
                - title
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  message: 'Task deleted successfully.'
                  data: null
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'Task deleted successfully.'
                  data:
                    type: string
                    example: null
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  success: false
                  message: 'Task not found'
                  data: null
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: 'Task not found'
                  data:
                    type: string
                    example: null
      tags:
        - 'Task Management'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the task.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
  -
    name: 'Task Management'
    description: ''
